version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .

mkdocs:
  configuration: doc/mkdocs.yml
