#!/usr/bin/env python3
"""
Quick plot for output/subray_grid.csv generated by ScanningDevice::prepareSimulation.
Shows subray offsets (projected to z=1) and reports dx, dy, area_z1.
Usage: python scripts/debug/plot_subray_grid.py [path/to/subray_grid.csv]
"""
import argparse
import csv
import pathlib
import sys

import matplotlib.pyplot as plt


def load_grid(path: pathlib.Path):
    xs, ys = [], []
    dx = dy = area = None
    with path.open() as f:
        reader = csv.reader(f)
        for row in reader:
            if not row:
                continue
            if row[0].startswith('#'):
                # parse header hints if present
                line = ','.join(row)
                if 'dx=' in line and 'dy=' in line:
                    try:
                        parts = line.replace('#', '').split(',')
                        for p in parts:
                            if 'dx=' in p:
                                dx = float(p.split('=')[1])
                            if 'dy=' in p:
                                dy = float(p.split('=')[1])
                            if 'area_z1=' in p:
                                area = float(p.split('=')[1])
                    except Exception:
                        pass
                continue
            if row[0] == 'index':
                continue
            try:
                _, x, y, area_z1 = row
                xs.append(float(x))
                ys.append(float(y))
                if area is None:
                    area = float(area_z1)
            except ValueError:
                continue
    return xs, ys, dx, dy, area


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('csv', nargs='?', default='output/subray_grid.csv',
                        help='Path to subray_grid.csv (default: output/subray_grid.csv)')
    args = parser.parse_args()

    path = pathlib.Path(args.csv)
    if not path.exists():
        print(f"File not found: {path}", file=sys.stderr)
        sys.exit(1)

    xs, ys, dx, dy, area = load_grid(path)
    if not xs or not ys:
        print("No points found in CSV", file=sys.stderr)
        sys.exit(1)

    fig, ax = plt.subplots(figsize=(6, 6))
    ax.scatter(xs, ys, s=12, c='tab:blue', alpha=0.7)
    ax.set_aspect('equal', adjustable='box')
    ax.set_xlabel('x offset @ z=1')
    ax.set_ylabel('y offset @ z=1')
    ax.ticklabel_format(style='plain', useOffset=False, axis='both')

    # Add a small margin around the data to keep it visible
    margin_x = (max(xs) - min(xs)) * 0.05 if len(xs) > 1 else 0.1
    margin_y = (max(ys) - min(ys)) * 0.05 if len(ys) > 1 else 0.1
    ax.set_xlim(min(xs) - margin_x, max(xs) + margin_x)
    ax.set_ylim(min(ys) - margin_y, max(ys) + margin_y)

    title = f"Subray grid: n={len(xs)}"
    if dx and dy:
        title += f" | dx={dx:.4g}, dy={dy:.4g}"
    if area:
        title += f" | area_z1={area:.4g} (area@R = area_z1*R^2)"
    ax.set_title(title)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()


if __name__ == '__main__':
    main()
