name: win-build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  USER_CONFIG: ${{github.workspace}}/.github/config/boost/user-config.jam

jobs:
  build-boost:
    runs-on: windows-2019

    defaults:
      run:
        working-directory: ${{github.workspace}}/lib

    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/lib/boost
            ${{github.workspace}}/.github/config/boost
          key: ${{ runner.os }}-boost.1.78


      - name: Set Up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Write Python 3.6 to user-config.jam
        run: |
          $pythonString = "using python `n`t: 3.6 `n`t: ${{env.pythonLocation}}\bin\python.exe `n`t: ${{env.pythonLocation}}\include `n`t: ${{env.pythonLocation}}\libs `n;" 
          echo $pythonString.replace("\", "\\") >> ${{env.USER_CONFIG}}

      - name: Set Up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Write Python 3.7 to user-config.jam
        run: |
          $pythonString = "using python `n`t: 3.7 `n`t: ${{env.pythonLocation}}\bin\python.exe `n`t: ${{env.pythonLocation}}\include `n`t: ${{env.pythonLocation}}\libs `n;" 
          echo $pythonString.replace("\", "\\") >> ${{env.USER_CONFIG}}

      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Write Python 3.8 to user-config.jam
        run: |
          $pythonString = "using python `n`t: 3.8 `n`t: ${{env.pythonLocation}}\bin\python.exe `n`t: ${{env.pythonLocation}}\include `n`t: ${{env.pythonLocation}}\libs `n;" 
          echo $pythonString.replace("\", "\\") >> ${{env.USER_CONFIG}}

      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Write Python 3.9 to user-config.jam
        run: |
          $pythonString = "using python `n`t: 3.9 `n`t: ${{env.pythonLocation}}\bin\python.exe `n`t: ${{env.pythonLocation}}\include `n`t: ${{env.pythonLocation}}\libs `n;" 
          echo $pythonString.replace("\", "\\") >> ${{env.USER_CONFIG}}

      - uses: suisei-cn/actions-download-file@v1
        id: downloadboost
        name: Download boost
        with:
          url: "https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.zip"
          target: lib/boost_1_78_0.zip

      - name: Extract boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          7z x lib/boost_1_78_0.zip -olib
          move lib/boost_1_78_0 lib/boost
      

      - uses: suisei-cn/actions-download-file@v1
        id: downloadzlib
        name: Download zlib
        with:
          url: "https://www.zlib.net/zlib1211.zip"
          target: lib/boost/zlib1211.zip

      - name: Debug output
        working-directory: ${{env.GITHUB_WORKSPACE}}
        id: output
        run: |
          Get-Content ${{env.USER_CONFIG}}
          tree .
          pwd

      - name: Build Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd lib/boost
          7z x zlib1211.zip   
          cmd.exe /c 'bootstrap.bat'
          .\b2.exe --user-config=${{env.USER_CONFIG}} -j6 -sNO_ZLIB=0 -sZLIB_INCLUDE="zlib-1.2.11" -sZLIB_SOURCE="zlib-1.2.11" address-model=64 link=static python=3.6,3.7,3.8,3.9
          

      - uses: suisei-cn/actions-download-file@v1
        id: downloadglm
        name: Download GLM
        with:
          url: "https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip"
          target: lib/glm-0.9.9.8.zip

      - name: Extract GLM
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          7z x lib/glm-0.9.9.8.zip -olib
          dir lib
          

      - uses: suisei-cn/actions-download-file@v1
        id: downloadgdal1
        name: Download GDAL (1/2)
        with:
          url: "https://download.gisinternals.com/sdk/downloads/release-1928-x64-gdal-3-4-1-mapserver-7-6-4-libs.zip"
          target: lib/gdal.zip


      - uses: suisei-cn/actions-download-file@v1
        id: downloadgdal2
        name: Download GDAL (2/2)
        with:
          url: "https://download.gisinternals.com/sdk/downloads/release-1928-x64-gdal-3-4-1-mapserver-7-6-4/gdal-304-1928-x64-core.msi"
          target: lib/gdal.msi

      - name: Extract GDAL
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd lib
          7z x gdal.zip -ogdal
          dir .
          dir gdal
          move gdal/include/boost gdal/include/boost-gdal

      - name: Install GDAL
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          dir lib
          Start-Process -FilePath C:\Windows\System32\msiexec.exe -ArgumentList "/i lib\gdal.msi /qn"  -Wait

      - uses: suisei-cn/actions-download-file@v1
        id: downloadlastools
        name: Download LAStools
        with:
          url: "https://lastools.github.io/download/LAStools.zip"
          target: lib/LAStools.zip

      - name: Extract LAStools
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd lib
          7z x LAStools.zip
          cd LAStools
          cmake -DCMAKE_BUILD_TYPE=Release .
          msbuild.exe LAStools.sln /p:Configuration=Release
          

      - uses: suisei-cn/actions-download-file@v1
        id: downloadscilab
        name: Download SciLab
        with:
          url: "https://www.scilab.org/download/6.1.0/scilab-6.1.0_x64.exe"
          target: scilab.exe

      - name: Install scilab
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          dir
          D:\a\helios\helios\scilab.exe /VERYSILENT /NORESTART
          dir C:\          

      - uses: suisei-cn/actions-download-file@v1
        id: downloadarmadillo
        name: Download Armadillo
        with:
          url: "http://sourceforge.net/projects/arma/files/armadillo-10.6.2.tar.xz"
          target: lib/armadillo.tar.xz

      - name: Install Armadillo
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd lib
          dir
          7z x armadillo.tar.xz
          7z x armadillo-10.6.2.tar
          dir
          move armadillo-10.6.2 armadillo
          cd armadillo
          $env:Path += ';C:\Program Files\scilab-6.1.0\bin'
          cmake -DCMAKE_BUILD_TYPE=Release .
          msbuild.exe armadillo.sln /p:Configuration=Release
          
      - name: Build HELIOS++
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          ((Get-Content -path src\helios_version.cpp -Raw) -replace '(^const char \* HELIOS_VERSION = ")(.*)(";)','$1$2 - ${{ github.head_ref }}.${{ github.sha }}$3') | Set-Content -Path src\helios_version.cpp
          cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_BINDING=1 -DPYTHON_VERSION=39 -DPYTHON_PATH=${{env.pythonLocation}} .
          msbuild.exe helios.sln /p:AdditionalDependencies='"C:\Program Files\scilab-6.1.0\bin\blasplus.lib;C:\Program Files\scilab-6.1.0\bin\lapack.lib"'  /p:IncludePath="C:\Program Files\scilab-6.1.0\bin" /p:Configuration=Release
          
